### ISSUE TITLE
Support for InputType and ArgsType decorators

### ISSUE THREAD

**Issue by teovillanueva** [incetarik/nestjs-graphql-zod#1]
Hey! I've been really looking into this project. I Thought it would be great if the library can support these two decorators. If you think it makes sense to add these two into the project let me know and I'll if I can work on it 💪

**Comment by incetarik** [comment]
@teovillanueva Yes of course! Thank you for your comment and this library is free and for all people to use, then why not adding new features to that? I would like to see that is improving. If you need any help or question, do not hesitate asking questions.

**Comment by incetarik** [comment]
@teovillanueva `InputType` support is added with new version as you can see [this example](https://github.com/incetarik/nestjs-graphql-zod#inputtype-example)
