### ISSUE TITLE
Share enums

### ISSUE THREAD

**Issue by Almaju** [incetarik/nestjs-graphql-zod#10]
Is there a way to define an enum once?

If I do this: 

```ts
const CivilityDto = z
  .enum(['MR', 'MRS', 'MISS'])
  .describe('Civility: Civility');
```

And then re-use this enum in different objects, I will get multiple enums in my schema.

**Comment by incetarik** [comment]
@Almaju yes! Recently developed this. Please see the CHANGELOG file.

**Comment by incetarik** [comment]
Simply `registerEnumType` manually and return it from the function described in CHANGELOG.

**Comment by Almaju** [comment]
Hello @incetarik ! Thanks for your answer.
I checked the code and the CHANGELOG but it's a bit confusing for me what these functions do even after checking the source code.
Are you supposed to do: `setDefaultEnumProvider(registerEnumType);`?
Would it be possible to add a small paragraph about this use-case in the doc or a test file?

**Comment by incetarik** [comment]
Hello @Almaju !

First of all, it is possible to set enum providers per decorator. 
Apart from that, the `setDefaultEnumProvider` is a function that register another function that will be returning the corresponding type of an enum. When a decorator do not take any custom enum (type) provider, this default type provider will be used.

If you see the the [relevant line here](https://github.com/incetarik/nestjs-graphql-zod/blob/c7864972e58f51822ee350336c4a170784faf579/src/helpers/build-enum-type.ts#L38), you see that the enum provider is given two arguments where the first one is the enum that is parsed from the zod schema and the second one is the properties about it such as its name, the name of the parent that enum belongs to and the description of the enum.

These are given to you to determine your custom type. What you could simply do is writing a function that will see the elements of the enum that is parsed from the zod and return an enum that you **previously** registered through `registerEnumType`.

```ts

const RegisteredEnums = {} // propertyName=EnumType

setDefaultEnumProvider((parsedEnumObject, details) => {
  // Write your logic here, an example:
  if (details.name in RegisteredEnums) {
    return RegisteredEnums[details.name]
  }

  // Returning nothing (undefined) will cause the lib to generate a type.
})
```

This may not be useful for all cases as I'm simply checking for its property name but you can develop it as you desire.
