### ISSUE TITLE
Where should I call setDefaultTypeProvider function?

### ISSUE THREAD

**Issue by dkjym** [incetarik/nestjs-graphql-zod#11]
I want to create a custom scalar for z.date() types.

When I call setDefaultTypeProvider inside a resolver file like the examples it works just fine, but I'd like to call it somewhere inside a common config file.

I tried calling it inside main.ts but it gave me the error below.

```
Error: Unsupported type info of Key("key") of Type("Date")
```

And here is the setDefaultTypeProvider I am calling

```
setDefaultTypeProvider((typeName) => {
    if (typeName === "Date")
      return new GraphQLScalarType({
        name: "DateTime",
      });
    return undefined;
  });
```

Where is the best to place to call this?
Thanks :)

**Comment by incetarik** [comment]
Hello! @dkjym 

What I would recommend you is calling this function before the `bootstrap` function is called, which is where the application starts serving.
Other than that I'd need to see if having `new` usage there causing this issue, could you please try to create it around, before the application comes here to evaluate the anonymous function you pass to `setDefaultTypeProvider`?

Maybe you could try something like this:

```ts
const DateType = new GraphQLScalarType({ name: "DateTime" });
setDefaultTypeProvider((typeName) => {
  if (typeName === "Date") { return DateType }
  
  return undefined
})
```

Something similar to this, if this works, tell me and I'll add this to somewhere around the readme or in the function documentation. I'm not sure right now if the scalar type should be registered (made known by the graphql server of nests) beforehand. When I'm back to my pc, I'll check this out and I'm thinking about writing a reminder/note for this.
But until that happens, you could try what I have mentioned.

Personally, I use `graphql-scalars` package in my projects and then use it like the following:
```ts
setDefaultTypeProvider(name => {
    while (name.startsWith('Optional<')) name = name.slice(9)
    while (name.startsWith('Nullable<')) name = name.slice(9)
    while (name.startsWith('Array<')) name = name.slice(6)

    if (name.startsWith('Record')) {
      return GraphQLJSONObject
    }
})
```

So it is why I'm just assuming that the `new` you use inside the function may cause this to be unknown, as I'm not using that in this example.

**Comment by dkjym** [comment]
I'm calling it before bootstrap(), with the example you've provided but still getting the same error.
Here is my exact main.ts file

```
import { NestFactory } from "@nestjs/core";
import { GraphQLISODateTime } from "@nestjs/graphql";
import { PrismaService } from "@src/modules/prisma/prisma.service";
import type { GraphQLScalarType } from "graphql";
import { setDefaultTypeProvider } from "nestjs-graphql-zod";

import { AppModule } from "./app.module";

const CustomMaps: Record<string, GraphQLScalarType> = {
  Date: GraphQLISODateTime, // decided to use the custom scalar nest/graphql provides
};

console.log("setDefaultTypeProvider");

setDefaultTypeProvider((name) => {
  // As the Optional, Nullable and Array types can be processed internally
  // you may want to get the underlying, actual type name.
  while (name.startsWith("Optional<")) name = name.slice(9);
  while (name.startsWith("Nullable<")) name = name.slice(9);
  while (name.startsWith("Array<")) name = name.slice(6);

  // return the corresponding custom scalar type
  return CustomMaps[name];
});

async function bootstrap() {
  const app = await NestFactory.create(AppModule);

  // enable shutdown hook
  const prismaService: PrismaService = app.get(PrismaService);
  prismaService.enableShutdownHooks(app);

  const port = process.env.PORT ? parseInt(process.env.PORT, 10) : 5000;
  await app.listen(port);
}

bootstrap();
```

When I move this to one of my resolver files it works.

**Comment by dkjym** [comment]
@incetarik Importing AppModule **after** calling setDefaultTypeProvider worked! :tada:

```ts
import { NestFactory } from "@nestjs/core";
import { GraphQLISODateTime } from "@nestjs/graphql";
import type { GraphQLScalarType } from "graphql";
import { setDefaultTypeProvider } from "nestjs-graphql-zod";

const CustomMaps: Record<string, GraphQLScalarType> = {
  Date: GraphQLISODateTime, // decided to use the custom scalar nestjs/graphql provides
};

setDefaultTypeProvider((name) => {
  // As the Optional, Nullable and Array types can be processed internally
  // you may want to get the underlying, actual type name.
  while (name.startsWith("Optional<")) name = name.slice(9);
  while (name.startsWith("Nullable<")) name = name.slice(9);
  while (name.startsWith("Array<")) name = name.slice(6);

  // return the corresponding custom scalar type
  return CustomMaps[name];
});

import { AppModule } from "./app.module"; // import this after setDefaultTypeProvider call

async function bootstrap() {
  const app = await NestFactory.create(AppModule);
  const port = process.env.PORT ? parseInt(process.env.PORT, 10) : 5000;
  await app.listen(port);
}
bootstrap();

```

**Comment by incetarik** [comment]
Thank you @dkjym.

This issue is definitely not about the library, as it is expected from the nodejs/bundlers to read those imports in-order, it is consumers job to be careful to register the default types before the nodejs/bundler read through other files that have those decorators applied. I'll write a note for this in the next version hopefully and people would be careful about this issue.

I'm closing this now, have a great day!
