### ISSUE TITLE
Provide example for union and nativeEnum

### ISSUE THREAD

**Issue by redappleorigin** [incetarik/nestjs-graphql-zod#16]
Could you provide an example of how to use a union?

Also, could you provide an example of how to use an enum, nativeEnum, and union with ZodArgs inline?

class ExampleResolver() {
    @Query(() => Boolean)
    inlineExample(
      @ZodArgs(zod.union([zod.number(), zod.string()])) stringOrNumberArray: (string | number)[],
      @ZodArgs(zod.enum(['url', 'id'])) urlOrId?: string,
    ) {
    }
  }

**Comment by incetarik** [comment]
Hello @redappleorigin!

After I check how it would be the best or possible on the GraphQL side, I'll provide what's needed.

**Comment by redappleorigin** [comment]
The nativeEnum is really easy to add, it's basically a copy and paste of your existing enum code in build-enum-type.ts:

```ts
else if (isZodInstance(ZodNativeEnum, type)) {
    const Enum = type.enum;

    let enumProvider = options.getEnumType ?? getDefaultEnumProvider();

    if (typeof enumProvider === 'function') {
      const replacement = enumProvider(Enum, {
        name: String(key),
        parentName: options.name,
        description: type.description,
      });

      if (typeof replacement === 'object' && Enum !== replacement) {
        return (typeInfo.type = replacement);
      }
    }

    const incompatibleKey = getFirstIncompatibleEnumKey(Enum);
    if (incompatibleKey) {
      throw new Error(
        `The value of the Key("${incompatibleKey}") of ${options.name}.${String(
          key,
        )} Enum was not valid`,
      );
    }

    const parentName = options.name;
    const enumName = withSuffix('Enum')(toTitleCase(key as string));
    const registerCount = getRegisterCount();

    registerEnumType(Enum, {
      name: toTitleCase(`${parentName}_${enumName}_${registerCount}`),
      description:
        type.description ?? `Enum values for ${options.name}.${String(key)}`,
    });

    return (typeInfo.type = Enum);
  }
  ```

**Comment by incetarik** [comment]
Hi @redappleorigin, agreed. Native enum is easy for sure and planning to add that in the next release, but I'm also wondering about the union types, but apart from that, I'll send this as soon as possible.

**Comment by incetarik** [comment]
Hi @redappleorigin !

NativeEnums are added, union types are still under development.
