### ISSUE TITLE
is z.date() supported?

### ISSUE THREAD

**Issue by kikinecek** [incetarik/nestjs-graphql-zod#17]
Hello,

I have struggle to make nestjs-graphql-zod work when my ZodObject contains Date type.

I have this in my z.object ` createdAt: z.date(),` and I get error every time I try to use it with `@QueryWithZod()` decorator.

Since I'm getting error `Unsupported type info of Key("createdAt") of Type("Date")` then it's not supported yet I guess.

Thanks for the answer.

**Comment by incetarik** [comment]
Hello @kikinecek! 

Please see #9 for description and #11 for solution.
