### ISSUE TITLE
Issues with MutationWithZod decorator causing unit tests to fail

### ISSUE THREAD

**Issue by liam-daley** [incetarik/nestjs-graphql-zod#18]
### Description

When using the `MutationWithZod` decorator in my NestJS project, I've noticed that unit tests which pass with the standard `@Mutation` and `@Args` decorators from `@nestjs/graphql` fail when using `MutationWithZod` from `nestjs-graphql-zod`.

### Steps to Reproduce

1. Create a NestJS service with a GraphQL resolver.
2. Use the `MutationWithZod` decorator with the appropriate Zod schema.
3. Write a unit test that invokes the mutation.
4. Run the test.

### Expected Behavior

The test should pass, and the mutation should return the expected object.

### Actual Behavior

The mutation returns an instance of `DynamicZodModel` instead of the expected object.

### Code Sample

```typescript
@MutationWithZod(feedbackResponseSchema)
async submitFeedback(
    @ZodArgs(feedbackInputSchema, 'input')
    input: ZodArgs.Of<typeof feedbackInputSchema>
): Promise<FeedbackResponseDto> {
    const isSubmitted = await this.feedbackService.submitFeedback(input);

    return { isSubmitted: isSubmitted === true };
}
```

In my unit tests, I expect the result to be either { isSubmitted: true } or { isSubmitted: false }, but instead, I get DynamicZodModel.

I've tried troubleshooting this by logging the returned values, and they do match my expectations within the resolver, but something seems to change afterward, leading me to believe there might be an issue with how the MutationWithZod decorator processes the result.

System Information:
OS: Windows 10
Node.js version: 18.17.1
NestJS version: 10.0.0
nestjs-graphql-zod version: 3.2.0

**Comment by incetarik** [comment]
Hi @liam-daley !

Could you please check it again with the [last version](https://github.com/incetarik/nestjs-graphql-zod/releases/tag/3.3.0)?
A new property `parseToInstance` is added.
