### ISSUE TITLE
Failed to get the correct parameter name

### ISSUE THREAD

**Issue by Darkhorse-Fraternity** [incetarik/nestjs-graphql-zod#19]
env:
  System:
    OS: macOS 13.3.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 221.46 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.18.2 - ~/.nvm/versions/node/v18.18.2/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.18.2/bin/yarn
    npm: 9.8.1 - ~/.nvm/versions/node/v18.18.2/bin/npm
    pnpm: 8.9.2 - ~/.nvm/versions/node/v18.18.2/bin/pnpm
    Watchman: 2023.10.09.00 - /usr/local/bin/watchman

<img width="909" alt="image" src="https://github.com/incetarik/nestjs-graphql-zod/assets/5756752/da0b6445-39d6-47e8-9bf1-72f731984193">

This is how I use it：

```ts
  @UseGuards(GqlAuthGuard)
  @MutationWithZod(PostSchema)
  async createPost(
    @UserEntity() user: User,
    @ZodArgs(CreatePostInput) data: ZodArgs.Of<typeof CreatePostInput>,
  ) {
    const newPost = this.prisma.post.create({
      data: {
        published: true,
        title: data.title,
        content: data.content,
        authorId: user.id,
      },
    });
    pubSub.publish("postCreated", { postCreated: newPost });
    return newPost;
  }
```

**Comment by incetarik** [comment]
Hello @Darkhorse-Fraternity!

The parameter names may not be inferred/read at runtime as they are not properties (bound to a context), instead, we may get their indices and it is how they work by default (as you have `arg_$INDEX`).
If you want to give them a name, you can. See the overloads of the `@ZodArgs` decorator and you will find what you are looking for.
