### ISSUE TITLE
 It is impossible to use the scheme with Date in inputZod

### ISSUE THREAD

**Issue by Opezdalgif** [incetarik/nestjs-graphql-zod#20]
I want to specify in the schema so that read_at has Date specified.
`export const UpdateMessageChema = CreateMessageShema.pick({offer_answer: true}).extend({
    id: z.string(), 
    read_at: z.date().nullable().optional()
})`
 But I get this error: "Unsupported type info of Key("read_at") of Type("Date")" in get-field-info-from-zod. Will it be possible to add Date type processing?

**Comment by incetarik** [comment]
Hello @Opezdalgif !

See #17 for similar case and I hope this will answer your question. Not only the `Date` will be supported in anyway you want, but any type would be working as long as they have their corresponding graphql types.
