### ISSUE TITLE
Off-topic: just for inspiration, my implementation for union types

### ISSUE THREAD

**Issue by kolpakov-p** [incetarik/nestjs-graphql-zod#21]
Hi!

I'm maintaining the similar package based on your code originally. Recently, I've introduced a solution that covers the issue with union types support.

I thought that my code might serve as a hint or, at least, inspire you.

Here are the main moments:

* https://github.com/kolpakov-p/zod-to-nestjs-graphql/pull/3/files#diff-a2a171449d862fe29692ce031981047d7ab755ae7f84c707aef80701b3ea0c80R42
* https://github.com/kolpakov-p/zod-to-nestjs-graphql/pull/3/files#diff-a0c2db6b32386065a522cac66cac451d6175a786d004453016bc675db0e6c811R194

Thank you for awesome package!

**Comment by incetarik** [comment]
Hi @kolpakov-p !

Thank you for your recommendation! I'll implement this and will mention your name too.
Have a nice day!

**Comment by brendenpalmer** [comment]
@incetarik Noticed this issue was closed as completed, but has support for union types been implemented and/or released yet? Thanks in advance!
