### ISSUE TITLE
Add Lightning Network as a donation option

### ISSUE THREAD

**Issue by marcusmmmz** [incetarik/nestjs-graphql-zod#23]
I wanted to donate a few bitcoins to your project but I saw there is no Lightning Network option. Adding a Lightning Network option allows people to donate smaller amounts of Bitcoin and pay less fees. If you don't know anything about Lightning, I recommend using the [coinos web wallet](https://coinos.io/marcusmmm), it's pretty simple and quite popular, you just create an account and can already receive. There's also [Wallet of Satoshi](https://www.walletofsatoshi.com/) for a mobile wallet, no account needed.

After you create a wallet you can use a static Lightning Address (also called LNURL) to receive bitcoins over Lightning:
![image](https://github.com/incetarik/nestjs-graphql-zod/assets/30752235/3f2da82f-88da-4caa-b325-bb762c56eb91)

If you end up creating a Lightning wallet, tell me and I'll donate a few coins!

**Comment by incetarik** [comment]
@marcusmmmz Thank you for letting me know this thing that I have not known before!

Yeah I did create an account on it and it is `incetarik@coinos.io` now. I'll update the library read-me soon as well.
Thank you and have a nice day.

**Comment by marcusmmmz** [comment]
@incetarik nice! Check out your new balance

**Comment by incetarik** [comment]
@marcusmmmz Received it! Thank you!
