### ISSUE TITLE
Add examples for Mutations

### ISSUE THREAD

**Issue by sschneider-ihre-pvs** [incetarik/nestjs-graphql-zod#4]
There are only query examples, please add one for Mutations like create, update, delete.

**Comment by incetarik** [comment]
> There are only query examples, please add one for Mutations like create, update, delete.

You can simply write `Mutation` instead of `Query` like `MutationWithZod`. The subscription is also the same. They have very same overloads for corresponding decorator overloads.

**Comment by sschneider-ihre-pvs** [comment]
But what about if none nullable competes with zod required?

**Comment by sschneider-ihre-pvs** [comment]
so if you have a field that is required for a database operation maybe even a primary key and it is allowed to be nullable, so in the graphql schema it needs to be nullable also. but in the zod schema either default null or required

**Comment by incetarik** [comment]
> so if you have a field that is required for a database operation maybe even a primary key and it is allowed to be nullable, so in the graphql schema it needs to be nullable also. but in the zod schema either default null or required

Could you please provide an example of what you want to mention? Because I think I need to get this well, it is not clear for me yet.

**Comment by sschneider-ihre-pvs** [comment]
|  id primary nullable | value  | 
|---|---|
|  [null] |  ---- |  
|  1 | "Hello World"  |

**Comment by incetarik** [comment]
The default values are also applied if you provide the default with the zod. For example:
```ts
const Scheme = z.object({
  id: z.string().optional().default('----')
}).describe('DbTable: Example')
```

With this scheme, it is expected to have the following GraphQL scheme:
```graphql
"""Example"""
model DbTable {
  id: String
}
```

As you see the `id` field is now `nullable`.

So you apply this scheme object to any method like:
```ts
class ResolverClass {
  @MutationWithZod(Scheme)
  method() {
    // actual logic here
  }
}
```

Now as you have used `.default(...)` call on the zod scheme above, now your field/property will have its default value. Therefore if nothing is given from the client, the default value will be used.
I hope this answers your question @sschneider-ihre-pvs.
