### ISSUE TITLE
All exceptions are bad exceptions.

### ISSUE THREAD

**Issue by miyagi389** [incetarik/nestjs-graphql-zod#6]
I would like to throw an error other than ZodError in my GraphQL query.

For example, the code would be as follows
https://github.com/miyagi389/nestjs-graphql-zod-examples/blob/5596be7ad1641ec253598959397a47906ebf4316/src/app.resolver.ts#L28-L30
```typescript
    @QueryWithZod(UserZod)
    async getUser(@ZodArgs(UserZodInput) input: ZodArgs.Of<typeof UserZodInput>) {
        if (input.userId < 0) {
            throw new NotFoundException(`userId not found: ${input.userId}`);
        }
        ...
```

When this code is executed, the expected GraphQL response is

```bash
curl --request POST \
    --header 'content-type: application/json' \
    --url http://localhost:3000/graphql \
    --data '{"query":"query GetUser($input: UserZodInput!) {\n  getUser(input: $input) {\n    name\n    age\n  }\n}","variables":{"input":{"userId":-1}}}' \
    | jq
```

Expected GraphQL response
```json
{
  "errors": [
    {
      "message": "userId not found: -1",
      "extensions": {
        "code": "404",
        "response": {
          "statusCode": 404,
          "message": "userId not found: -1",
          "error": "Not Found"
        }
      }
    }
  ],
  "data": null
}
```

but the actual GraphQL response is as follows
```json
{
  "errors": [
    {
      "message": "Bad Request",
      "extensions": {
        "code": "BAD_USER_INPUT",
        "response": {
          "statusCode": 400,
          "message": "Bad Request"
        }
      }
    }
  ],
  "data": null
}
```

I would guess that the part of the source code responsible is here.
https://github.com/incetarik/nestjs-graphql-zod/blob/master/src/decorators/decorate-with-zod-input.ts#L39

**Comment by incetarik** [comment]
@miyagi389 Hello! Thank you for your feedback, I'll change this as you have mentioned and will notify you again.
Have a nice day.

**Comment by incetarik** [comment]
Hello @miyagi389 

With the new changes, the following will happen:
- If the input validation is failed, `BadRequestException` with code `400` will still be thrown and will contain the expected validation details.
- If the output validation is failed, the same will happen.
- If custom exception is thrown from the body of the method, the exception will be forwarded as it is, for example you can throw a `ConflictException`.
- If an `Error` is thrown, then it will be however the NestJS handles that, therefore it will be an `Internal Server Error`.

With the version `2.0.2` the behavior will be as described above.
You can see the changes [here](https://github.com/incetarik/nestjs-graphql-zod/compare/2.0.1...2.0.2).

**Comment by miyagi389** [comment]
Hello @incetarik 

I have confirmed that it works as expected.
Thank you for your response!
