### ISSUE TITLE
Duplicate input types created when using same schema in multiple ZodArgs

### ISSUE THREAD

**Issue by AnsonT** [incetarik/nestjs-graphql-zod#8]
Define a resolver with multiple mutations that take the same ZodArgs schema:

@Mutation(() => Boolean)
method1(@ZodArgs(SomeInputSchema) input: ...)

@Mutation(() => Boolean)
method2(@ZodArgs(SomeInputSchema) input: ...)

**Comment by incetarik** [comment]
Hi @AnsonT, this is actually expected behavior, try to keep one instance of it such as:
```ts
const CustomParamDecorator = ZodArgs(SomeInputSchema)

@Mutation(() => Boolean)
method1(@CustomParamDecorator input: ...) { ... }

@Mutation(() => Boolean)
method2(@CustomParamDecorator input: ...) { ... }
```

If this solves your problem then it is good, but I'll prevent generating duplicate input types for sure and will push it when I'm free.

**Comment by incetarik** [comment]
Hello @AnsonT !

With latest version [2.0.3](https://github.com/incetarik/nestjs-graphql-zod/releases/tag/2.0.3) this is now fixed and you can use same schema for `ZodArgs` in place and it will not cause any problem any more.
