### ISSUE TITLE
Doesn't create decorator for ZodDate type.

### ISSUE THREAD

**Issue by BelijDev** [incetarik/nestjs-graphql-zod#9]
Hi!

For schema:
```
import { z } from 'zod';
const testSchema = z.object({
  dateField: z.date(),
});
type TestType = z.infer<typeof testSchema>;
```
and  query:
```
  @Query(() => String)
  async test(@ZodArgs(testSchema) t: TestType) {
    return 'Ok';
  }
```

produces exception:
```
.../node_modules/nestjs-graphql-zod/src/helpers/parse-shape.ts:100
      throw new Error(`"${key}" cannot be processed`)
            ^
Error: "dateField" cannot be processed
```

**Comment by incetarik** [comment]
Hello, thank you for your message.

That is expected as the `Date` may have different representations such as full ISO date string or a timestamp. As there is no uniquely specified data type for `Date` for `GraphQL`, it is normal for the library to throw this exception. I think the best would be using a converter from any type you desire to date. For example, you may use timestamp which is a number and validate that to be in the range you want to be and then convert to date back and forth as you wish. The generated `GraphQL` schema would need to define the `Date` scalar type which may also not be compatible with other fields if any of your fields in also have custom `Date` format. For such cases, the library does not provide an alternative.

Maybe in the future I may add a way to let the developer to choose what implementation will be used for that custom `scalar` type during the conversion and validation. But for now, it is not implemented.
